#!/usr/bin/env bash
# Release validation script for vllm-oxide v0.1
#
# Run on a GPU machine (sm_89+) before tagging a release.
# This is the RELEASE GATE — not CI.
#
# Usage (thresholds must come from reviewed release evidence):
#   COMPARISON_POLICY_VERSION=same-prefix-v1 \
#   L1_NEAR_TIE_MAX_ABS_LOGIT_GAP=<value> L2_ATOL=<value> \
#   ./tools/validate-release.sh /path/to/Qwen3-0.6B [goldens-v0.1]

set -euo pipefail

MODEL_PATH="${1:?Usage: $0 <model-path> [release-tag]}"
RELEASE_TAG="${2:-goldens-v0.1}"
SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
GOLDEN_OUTPUT="/tmp/vllm-oxide-goldens-release"
COMPARISON_POLICY_VERSION="${COMPARISON_POLICY_VERSION:?Set reviewed policy version}"
L1_NEAR_TIE_MAX_ABS_LOGIT_GAP="${L1_NEAR_TIE_MAX_ABS_LOGIT_GAP:?Set reviewed L1 threshold}"
L2_ATOL="${L2_ATOL:?Set the reviewed L2 threshold}"

echo "════════════════════════════════════════════"
echo "  vllm-oxide v0.1 Release Validation"
echo "════════════════════════════════════════════"
echo "  Model:      $MODEL_PATH"
echo "  Release:    $RELEASE_TAG"
echo "  Goldens:    $GOLDEN_OUTPUT"
echo ""

# Step 1: Generate golden fixtures (both oracles)
echo "── Step 1: Generating golden fixtures ──"
cd "$SCRIPT_DIR/tools/golden-gen"
uv sync
uv run python -m golden_gen generate \
    --output-dir "$GOLDEN_OUTPUT"
echo ""

# Step 2: Record calibration observations and explicit comparison policy
echo "── Step 2: Calibrating tolerance ──"
uv run python -m golden_gen calibrate \
    --manifest-dir "$GOLDEN_OUTPUT" \
    --comparison-policy-version "$COMPARISON_POLICY_VERSION" \
    --l1-near-tie-max-abs-logit-gap "$L1_NEAR_TIE_MAX_ABS_LOGIT_GAP" \
    --l2-atol "$L2_ATOL"
echo ""

# Step 3: Build the comparison crate (release mode)
echo "── Step 3: Building comparison crate ──"
cd "$SCRIPT_DIR"
cargo build --release -p vllm_oxide_test
echo ""

# Step 4: Run the comparison
echo "── Step 4: Running golden comparison ──"
cargo run --release -p vllm_oxide_test -- \
    --model-path "$MODEL_PATH" \
    --manifest "$GOLDEN_OUTPUT/manifest.json" \
    --prompts-dir "$SCRIPT_DIR/tools/golden-gen/prompts"
echo ""

# Step 5: Upload to GitHub Release (if PASS)
echo "── Step 5: Uploading Release asset ──"
gh release create "$RELEASE_TAG" \
    --repo RedHeartSecretMan/vllm-oxide \
    --title "Golden fixtures — $RELEASE_TAG" \
    --notes "Generated by tools/golden-gen/. See manifest.json in this release for provenance." \
    "$GOLDEN_OUTPUT/manifest.json" "$GOLDEN_OUTPUT"/*.safetensors

echo ""
echo "════════════════════════════════════════════"
echo "  Release $RELEASE_TAG published"
echo "════════════════════════════════════════════"
